on:
  push:
    branches:
    - c502
  workflow_dispatch:
  
jobs:
  build_proxy_list:
    permissions:
      contents: write
    name: build_proxy_list
    runs-on: ubuntu-22.04
    steps:
    - name: Get repo
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
  
    - name: Get custom v2dat
      run: curl -L https://github.com/C502/v2dat/releases/latest/download/v2dat --output v2dat && chmod +x v2dat

    - name: Build dat 
      run: go run ./ --datapath=./data

    - name: Extract txt
      run: mkdir out && ./v2dat unpack geosite --nocn ./dlc.dat -o out -f 'geolocation-!cn' && mv './out/dlc_geolocation-!cn.txt' 'dlc_geolocation-!cn.txt'

    - name: Upload file to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'dlc_geolocation-!cn.txt'
        path: './dlc_geolocation-!cn.txt'

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: out
        artifacts: 'dlc_geolocation-!cn.txt'

