on:
  push:
    branches:
    - C502
  workflow_dispatch:
  
jobs:
  build_proxy_list:
    name: build_proxy_list
    runs-on: ubuntu-22.04
    steps:
    - name: Get repo
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
  
    - name: Get custom v2dat
      run: curl -O https://github.com/C502/v2dat/releases/latest/download/v2dat --output v2dat && chmod +x v2dat

    - name: Build dat 
      run: go run ./ --datapath=./data

    - name: Extract txt
      run: ./v2dat unpack geosite --nocn ./dlc.dat -o out -f 'geolocation-!cn'

    - name: Upload file to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'dlc_geolocation-!cn.txt'
        path: './out/dlc_geolocation-!cn.txt'

    
    
